---
title: "data_scraping"
author: "Yuxuan Du"
date: "2023-10-12"
output: html_document
---

```{r}
library(rvest)
library(httr)

```

```{r}
nsduh_url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

nsduh_html = read_html(nsduh_url)
```

```{r}
marj_ise_df = 
  nsduh_html |>
  html_table()|>
  first()|>
  slice(-1)
```

```{r}
swm_url = "https://www.imdb.com/list/ls070150896/"

swm_html = read_html(swm_url)
```

```{r}
swm_title = 
  swm_html |>
  html_elements(".lister-item-header a")|>
  html_text()

swm_gross_rev = 
  swm_html |>
  html_elements(".text-muted .ghost~ .text-muted+ span")|>
  html_text()

swm_df = 
  tibble(
    title = swm_title, 
    gross_rev = swm_gross_rev
  )
```


## API
```{r}
nyc_water = 
  GET("https://data.cityofnewyork.us/resource/ia2d-e54m.csv") |> 
  content("parsed")
```


```{r}
brfss_smart2010 = 
  GET("https://chronicdata.cdc.gov/resource/acme-vg9e.csv", 
      query = list("$limit" = 5000)) |> 
  content("parsed")
```

```{r}
poke = 
  GET("http://pokeapi.co/api/v2/pokemon/1") |>
  content()
```